[book]
title = "Google Data Analytics Capstone 1"
author = "Vasco Ferreira"
description = "The capstone for the course Google Data Analytics on Coursera."
language = "en"
multilingual = false
src = "docs-markdown"

[build]
build-dir = "docs"

[output.html]
additional-css = ["docs-markdown/css/styles.css"]
mathjax-support = true