---
title: "01 - Data Merging"
author: "Vasco Ferreira"
date: "7/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries needed

```{r}
library(tidyverse)
```

## The data

The data was fetched from [Divvy tripdata](https://divvy-tripdata.s3.amazonaws.com/index.html).
The zip files were store in `../data/external` and extracted into the folder
`../data/raw`.

## Load the data files

The dates of the files go from `2020-04` to `2021-05` so, load all the files and
concatenate the dataframes to make a single dataframe with all the trip data.

```{r}
# Skip the first as we will load it separately
files_date <- c(
  "202005",
  "202006",
  "202007",
  "202008",
  "202009",
  "202010",
  "202011",
  "202012",
  "202101",
  "202102",
  "202103",
  "202104",
  "202105"
)

col_types = list(
  col_character(),
  col_character(),
  col_datetime(format = "%Y-%m-%d %H:%M:%S"),
  col_datetime(format = "%Y-%m-%d %H:%M:%S"),
  col_character(),
  col_character(),
  col_character(),
  col_character(),
  col_double(),
  col_double(),
  col_double(),
  col_double(),
  col_character()
)

tripdata <- read_csv("../data/raw/202004-divvy-tripdata.csv", col_types = col_types)

for(d in files_date)
{
  filename = sprintf("../data/raw/%s-divvy-tripdata.csv", d)
  filedata = read_csv(filename, col_types = col_types)
  tripdata = bind_rows(tripdata, filedata)
}
```

Check the new dataframe.

```{r}
tripdata
```

Save the data to a csv file.

```{r}
write_csv(tripdata, "../data/processed/01_tripdata.csv")
```

